# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJmHNxz7nqnmg0qMV2S-v8LeQCYw8SvI
"""

from data_loader import load_option_data, clean_data
from yield_curve import fetch_yield_curve, get_rate
from black_scholes import black_scholes_call
from iv_surface import build_iv_surface, plot_surface
from cev_model import calibrate_cev, C

# =========================
# MAIN
# =========================

def main():

# get the ticke
  ticker = input("Enter ticker (e.g. ^SPX, AAPL): ").strip()

  S0, maturities, raw = load_option_data(ticker)
  df = clean_data(raw, S0)

  print(f"\nSpot: {S0:.2f}")
  print(f"Options used: {len(df)}")

  print("\nAvailable maturities:")
  for m in maturities:
    print(m)

  maturity = input("\nChoose maturity: ").strip()
  if maturity not in maturities:
    print("Invalid maturity.")

  # compute T
  today = pd.Timestamp.today().normalize()
  T = (pd.to_datetime(maturity) - today).days / 365

  yc_mats, yc_rates = fetch_yield_curve()
  # build curve

  print("Curve:")
  for m, r in zip(yc_mats, yc_rates):
    print(f"{m:.2f}Y -> {r:.4%}")

  r= get_rate(T, yc_mats, yc_rates )
  print("\nInterpolated rate:", r)


  K = float(input("Strike: "))


  # plot surface
  plot_surface(df)

  # build IV surface
  iv_func = build_iv_surface(df)

  r = get_rate(T, yc_mats, yc_rates)
  k = np.log(S0 / K)

  sigma = iv_func(k, T)

  call = black_scholes_call(S0, K, T, r, sigma)
  put = call - S0 + K*np.exp(-r*T)

  print("\n=== Black-Scholes ===")
  print(f"IV: {sigma:.4f}")
  print(f"Call: {call:.4f}")
  print(f"Put: {put:.4f}")

  # CEV calibration
  res = calibrate_cev(df, S0, yc_mats, yc_rates)

  sigma_cev, beta = res.x

  cev_price = C(S0, K, T, r, sigma_cev, beta)
  put_local = cev_price - S0 + K*np.exp(-r*T)


  print("\n=== Results Using Local Volatility===")
  print(f"Local Vol: {res.x[0]:.4f}")
  print(f"Beta: {res.x[1]:.4f}")
  print(f"Call Price: {cev_price:.4f}")
  print(f"Put Price: {put_local:.4f}")



if __name__ == "__main__":
    main()

