# -*- coding: utf-8 -*-
"""black_scholes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lMEhuEXIMB1EiVl4QexUuv9RrKOvffmW
"""

# =========================
# black_scholes_call
# =========================

def black_scholes_call(S, K, T, r, sigma):
    """
    :param S: Asset price
    :param K: Strike price
    :param T: Time to maturity
    :param r: risk-free rate (treasury bills)
    :param sigma: volatility
    :return: call price
    """
    N_prime = norm.pdf
    N = norm.cdf
    # Black-Scholes Formula
    d1 = (np.log(S / K) + (r + sigma**2 / 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)

    call = S * N(d1) - N(d2) * K * np.exp(-r * T)
    return call

