# -*- coding: utf-8 -*-
"""cev_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCEL91ra76e1-msEOK-sMu0ChDBzb4dG
"""

# =========================
# Local Volatility with callibration
# =========================

def C(S0, strike, T, r, sigma, beta):
  zb = 2 + 2/(2-beta)
  kappa = 2 *r/(sigma **2 * 2*(2-beta)* (np.exp(r*(2-beta)*T)-1))
  x = kappa * S0 ** (2-beta)*np.exp(r*(2-beta) * T)
  y = kappa * strike **(2-beta)
  return S0*(1-ncx2.cdf(2*y,zb,2*x)) - strike*np.exp(-r*T)*(ncx2.cdf(2*x,zb-2,2*y))

def calibrate_cev(df, S0, yc_mats, yc_rates):

    def error(params):
        sigma, beta = params

        model = []
        market = df['Option_Price'].values

        for _, row in df.iterrows():
            T = row['Time_to_Maturity']
            K = row['strike']
            r = get_rate(T, yc_mats, yc_rates)

            model.append(C(S0, K, T, r, sigma, beta))

        return mean_squared_error(market, model)

    res = minimize(
        error,
        x0=(0.5, 0.7),
        bounds=((0.01,2),(0,1.9)),
        method='L-BFGS-B'
    )

    return res

