# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aGaymNXGlGJEbpPVxoAkLnnpPK6lEhUL
"""

# =========================
# Fetch + Clean Data
# =========================

def load_option_data(ticker):
    tk = yf.Ticker(ticker)

    try:
        maturities = tk.options
        if len(maturities) == 0:
            raise ValueError("No options found.")
    except:
        raise ValueError("Invalid ticker.")

    spot = yf.download(ticker, period="5d", auto_adjust= False)["Adj Close"].dropna().iloc[-1] # underlying current value of the stock we compute mark-to market

    all_calls = []

    for m in maturities:
        chain = tk.option_chain(m)
        calls = chain.calls.copy()
        calls["maturity"] = pd.to_datetime(m)
        all_calls.append(calls)

    df = pd.concat(all_calls, ignore_index=True)

    return float(spot), maturities, df

def clean_data(df, S0):
    today = pd.Timestamp.today().normalize()

    df["Time_to_Maturity"] = (df["maturity"] - today).dt.days / 365
    df["Option_Price"] = (df["bid"] + df["ask"]) / 2  # option price
    df["Moneyness"] = np.log(S0 / df["strike"])


    df = df[
        (df["bid"] > 0) &
        (df["ask"] > 0) &
        (df["Time_to_Maturity"] > 0.24) & # not too close nor to far in the future between three month to one year
        (df["Time_to_Maturity"] < 2.0) &
        (df["volume"].fillna(0) > 5) &
        (df['Moneyness']> -0.1 ) &    # Moneyness  # only consider options within a certain range of the current price , most options that are most traded
        (df['Moneyness']< 0.8) &
        (df['openInterest'] > 10) &
        (df['impliedVolatility'] > 0.05)
    ]

    return df[['impliedVolatility','Time_to_Maturity', 'Moneyness', 'strike', 'Option_Price']].dropna()

