# -*- coding: utf-8 -*-
"""iv_surface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r4BpT-wIHspLi1JL9x_qXpeM7yyRtS1O
"""

# =========================
# IV Surface Interpolation
# =========================

def build_iv_surface(df):
    points = list(zip(df['Moneyness'], df['Time_to_Maturity']))
    values = df['impliedVolatility']

    interp = LinearNDInterpolator(points, values)

    def iv(k, T):
        val = interp(k, T)
        if np.isnan(val):
            # fallback: nearest neighbor
            dist = (df['Moneyness']-k)**2 + (df['Time_to_Maturity']-T)**2
            return df.iloc[np.argmin(dist)]['impliedVolatility']
        return float(val)

    return iv

# =========================
# Plot IV Surface
# =========================

def plot_surface(df):
    fig = plt.figure(figsize=(10, 7))
    ax = fig.add_subplot(111, projection='3d')

    surf = ax.plot_trisurf(
        df['Moneyness'],
        df['Time_to_Maturity'],
        df['impliedVolatility']*100,
        cmap=plt.cm.viridis
    )

    ax.set_xlabel("Moneyness (log)")
    ax.set_ylabel("Maturity (T)")
    ax.set_zlabel("IV (%)")

    plt.show()

