# -*- coding: utf-8 -*-
"""yield_curve.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2wviVr0p7JVNa9OgkSk5xBoybXhLdst
"""

# =========================
# Fetch Treasury Yields
# =========================

def fetch_yield_curve():
    """
    Fetch US Treasury yields from FRED
    Returns maturities (years) and rates (decimal)
    """

    series = {
        "DGS1MO": 1/12,
        "DGS3MO": 3/12,
        "DGS6MO": 6/12,
        "DGS1": 1,
        "DGS2": 2,
        "DGS5": 5,
        "DGS10": 10
    }

    end = dt.datetime.today()
    start = end - dt.timedelta(days=10)

    data = {}

    for code, maturity in series.items():
        try:
            df = pdr.DataReader(code, "fred", start, end)
            value = df.dropna().iloc[-1, 0] / 100  # convert % → decimal
            data[maturity] = value
        except:
            continue

    # sort by maturity
    maturities = np.array(sorted(data.keys()))
    rates = np.array([data[m] for m in maturities])

    return maturities, rates

# =========================
# Interpolation
# =========================

def get_rate(T, maturities, rates):
    """
    Interpolate rate for maturity T

    """
    curve, status = calibrate_ns_ols(maturities, rates, tau0=1.0)
    return float(curve(T))

